create database organisation;
use organisation;

create table employee(
fname varchar(20),
minit varchar(1),
lnane varchar(20),
ssn varchar(20),
dob date,
salary float,
gender varchar(20),
address varchar(20),
superssn varchar(10),
dno varchar(10)
);

rename table employee to worker;
desc worker;
ALTER TABLE worker ADD COLUMN PROJECT_NAME VARCHAR(20);
ALTER TABLE worker DROP COLUMN PROJECT_NAME;
drop table worker;
desc worker;


CREATE TABLE PROJECT(
PNAME VARCHAR(20),
PNAME VARCHAR(20),
PNUMBER VARCHAR(20),
PLOCATION VARCHAR(20),
DNUM VARCHAR(20),
POWNER VARCHAR(20),
HOURS INT,
MGRSSN VARCHAR(20),
DNAME VARCHAR(20),
FNAME VARCHAR(20),
LNAME VARCHAR(20)
);

RENAME TABLE PROJECT TO ASSGINMENT;
DESC ASSGINMENT;
ALTER TABLE ASSGINMENT ADD COLUMN HIKE_SALARY INT;
ALTER TABLE ASSGINMENT DROP COLUMN HIKE_SALARY;
ALTER TABLE ASSGINMENT DROP COLUMN LNAME;

alter table ASSGINMENT rename column pname to project_name;

CREATE TABLE WORKS_ON(
PNAME VARCHAR(20),
PNUMBER VARCHAR(20),
PLOCATION VARCHAR(20),
DNUM VARCHAR(20),
POWNER VARCHAR(20),
HOURS INT,
MGRSSN VARCHAR(20),
address varchar(20),
superssn varchar(10),
dno varchar(10)
);
ALTER TABLE WORKS_ON ADD COLUMN ONSITE_AVAILABLE VARCHAR(20);
ALTER TABLE WORKS_ON DROP COLUMN ADDRESS;
ALTER TABLE WORKS_ON DROP COLUMN DNUM;

CREATE TABLE DEPARTMENT(
dNAME VARCHAR(20),
dNUMBER VARCHAR(20),
dLOCATION VARCHAR(20),
DNUM VARCHAR(20),
LEAD_NAME VARCHAR(20),
HOURS INT,
MGRSSN VARCHAR(20),
address varchar(20),
superssn varchar(10),
dno varchar(10)
);

ALTER TABLE DEPARTMENT ADD COLUMN DESIGNATION VARCHAR(20);
ALTER TABLE DEPARTMENT DROP COLUMN ADDRESS;
ALTER TABLE DEPARTMENT DROP COLUMN DNO;


alter table department modify column mgrssn int; 

